apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  strategy: {}
  template:
    metadata:
      labels:
        app: web
    spec:
      volumes:
      - name: mycm
        configMap:
          name: myconfig
      containers:
      - image: nginx
        name: nginx
        volumeMounts:
        - name: mycm
          mountPath: /cm
